<?php

namespace Bootstrap;

use Zend_Controller_Request_Abstract;
use Zend_Controller_Response_Abstract;

class BootstrapController extends \Pimcore\Controller\Action {
    
    public function accordionAction () 
    {

    }
    
    public function columnsAction () 
    {

    }
    
    public function contentAction () 
    {

    }
    
    public function imageAction()
    {
        
    }
    
    public function panelAction () 
    {

    }
    
    public function alertAction()
    {

    }

    public function __construct(Zend_Controller_Request_Abstract $request, Zend_Controller_Response_Abstract $response, array $invokeArgs = array())
    {
        parent::__construct($request, $response, $invokeArgs); // TODO: Change the autogenerated stub
    }
}
